### ISSUE TITLE
Consider removing support for creating UUID versions 1 and 3

### ISSUE THREAD

**Issue by johnwcowan** [weinholt/uuid#1]
You already note that version 4 UUIDs are better than version 1, "except when used as namespaces".  I don't understand what makes namespace use any different from any other use of UUIDs.  I see no benefit to keeping version 1.

Now that SHA1 is thoroughly broken, version 3 UUID generators should be removed in favor of UUID 5.

**Comment by weinholt** [comment]
I can't find the source of the text you're quoting. I don't normally remove features. MD5 and SHA-1 are broken for certain uses, I don't believe this is one of them. The different UUID versions are all present in the latest Python standard library, I think they would have been removed from there if were was a problem with them.
